name: Build
on:
  push:
    branches-ignore:
      - '**-wip'
  pull_request:

jobs:
  make:
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository)
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - name: Prepack
        run: pnpm prepack
      - name: Publish
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: pnpm pkg-pr-new publish --package-manager=pnpm --pnpm 'packages/@srcdex-*'
